"""WatchDog - Decoy Content Generator

DECOY DATA: All content generated by this module is completely fake.
This is used to create realistic-looking canary files for authorized
security monitoring. No real credentials or personal data are generated.
"""

import os
import random
import string
import json


class DecoyGenerator:
    """Generates realistic-looking decoy files to make canaries convincing.

    All generated content is completely fake and for authorized security
    monitoring purposes only.
    """

    def __init__(self):
        self.decoy_templates = {
            'passwords': self._passwords_content,
            'financial': self._financial_content,
            'credentials': self._credentials_content,
            'crypto': self._crypto_content,
            'personal': self._personal_content,
            'documents': self._documents_content,
        }

    def generate(self, decoy_type='passwords'):
        """Generate fake decoy content.

        Returns completely fake data for authorized security monitoring only.
        """
        generator = self.decoy_templates.get(decoy_type, self._passwords_content)
        return generator()

    def _random_string(self, length=12):
        return ''.join(random.choices(string.ascii_letters + string.digits, k=length))

    def _random_email(self):
        # Using obviously fake domains for decoy content
        domains = ['example.com', 'test.invalid', 'fake.mail', 'demo.local']
        return f"{self._random_string(8)}@{random.choice(domains)}"

    def _passwords_content(self):
        """Generate fake password file content.

        ALL DATA BELOW IS COMPLETELY RANDOM AND FAKE.
        """
        lines = [
            "# DECOY FILE - ALL DATA IS RANDOMLY GENERATED",
            "# This is a security canary file for authorized monitoring",
            "# Personal Passwords - DO NOT SHARE",
            "# Last updated: 2024-12-15",
            "",
            "## Email Accounts (FAKE)",
        ]
        for _ in range(5):
            lines.append(f"{self._random_email()} : {self._random_string(16)}")
        lines.extend([
            "",
            "## Banking (FAKE DATA)",
            f"Chase: user{random.randint(100,999)} / Pass{''.join(random.choices(string.ascii_uppercase + string.digits, k=12))}",
            f"Wells Fargo: {self._random_string(8)} / {''.join(random.choices(string.ascii_letters + string.digits + '!@#$%', k=14))}",
            f"Coinbase: {self._random_email()} / {self._random_string(20)}",
            "",
            "## Social Media (FAKE DATA)",
            f"Instagram: {self._random_string(10)} / {self._random_string(14)}",
            f"Twitter: @{self._random_string(8)} / {self._random_string(12)}",
            f"Facebook: {self._random_email()} / Pass{random.randint(1000,9999)}!",
            "",
            "## WiFi (FAKE DATA)",
            f"Home Network: {self._random_string(10)}",
            f"Office: OfficeWifi{random.randint(100,999)}",
        ])
        return '\n'.join(lines)

    def _financial_content(self):
        """Generate fake financial records content.

        ALL DATA BELOW IS COMPLETELY RANDOM AND FAKE.
        """
        lines = [
            "# DECOY FILE - ALL DATA IS RANDOMLY GENERATED",
            "# This is a security canary file for authorized monitoring",
            "# Financial Records - CONFIDENTIAL",
            "",
            "## Bank Accounts (FAKE DATA)",
            f"Checking: ****{random.randint(1000,9999)} - Balance: ${random.randint(5000,50000):,.2f}",
            f"Savings: ****{random.randint(1000,9999)} - Balance: ${random.randint(10000,100000):,.2f}",
            "",
            "## Credit Cards (FAKE - NOT REAL CARD NUMBERS)",
            f"Card: XXXX-XXXX-XXXX-{random.randint(1000,9999)}",
            f"Card: XXXX-XXXX-XXXX-{random.randint(1000,9999)}",
            "",
            "## Investments (FAKE DATA)",
            f"401k: ${random.randint(50000,500000):,.2f}",
            f"Brokerage: ${random.randint(10000,200000):,.2f}",
            "",
            "## Tax Info (FAKE DATA)",
            f"SSN: XXX-XX-{random.randint(1000,9999)}",
            f"Last filing: {random.randint(2020,2024)}",
        ]
        return '\n'.join(lines)

    def _credentials_content(self):
        """Generate fake credentials content.

        ALL DATA BELOW IS COMPLETELY RANDOM AND FAKE.
        """
        lines = [
            "# DECOY FILE - ALL DATA IS RANDOMLY GENERATED",
            "# This is a security canary file for authorized monitoring",
            "# Saved Credentials (FAKE DATA)",
            "",
            "## Server Access (FAKE DATA)",
            f"SSH: root@192.168.1.{random.randint(1,254)} - Key: ~/.ssh/id_rsa",
            f"VPN: vpn.company.com - {self._random_string(8)} / {self._random_string(12)}",
            "",
            "## Cloud Services (FAKE DATA - NOT REAL KEYS)",
            f"AWS Key: FAKE{self._random_string(16)}",
            f"AWS Secret: {self._random_string(40)}",
            f"GCP Service Account: {self._random_email()}",
            "",
            "## Database (FAKE DATA)",
            f"MySQL: admin / db_pass_{self._random_string(8)}",
            f"MongoDB: mongodb://{self._random_string(6)}:{self._random_string(10)}@localhost:27017",
        ]
        return '\n'.join(lines)

    def _crypto_content(self):
        """Generate fake crypto wallet content.

        ALL DATA BELOW IS COMPLETELY RANDOM AND FAKE.
        """
        lines = [
            "# DECOY FILE - ALL DATA IS RANDOMLY GENERATED",
            "# This is a security canary file for authorized monitoring",
            "# Crypto Wallets - TOP SECRET (FAKE DATA)",
            "",
            "## Bitcoin (FAKE - NOT REAL WALLET)",
            f"Address: 1{self._random_string(33)}",
            f"Private Key: {self._random_string(64)}",
            "",
            "## Ethereum (FAKE - NOT REAL WALLET)",
            f"Address: 0x{self._random_string(40)}",
            f"Private Key: {self._random_string(64)}",
            "",
            "## Solana (FAKE - NOT REAL WALLET)",
            f"Address: {self._random_string(44)}",
            f"Private Key: {self._random_string(64)}",
            "",
            "## Seed Phrase (FAKE - NOT REAL)",
            f"{self._random_string(8)} {self._random_string(6)} {self._random_string(7)} {self._random_string(5)} {self._random_string(8)} {self._random_string(6)} {self._random_string(7)} {self._random_string(5)} {self._random_string(8)} {self._random_string(6)} {self._random_string(7)} {self._random_string(5)}",
        ]
        return '\n'.join(lines)

    def _personal_content(self):
        """Generate fake personal notes content.

        ALL DATA BELOW IS COMPLETELY RANDOM AND FAKE.
        """
        lines = [
            "# DECOY FILE - ALL DATA IS RANDOMLY GENERATED",
            "# This is a security canary file for authorized monitoring",
            "# Personal Notes - Private (FAKE DATA)",
            "",
            "## Travel Plans (FAKE DATA)",
            f"Flight: AA{random.randint(1000,9999)} - Dec {random.randint(15,30)}",
            f"Hotel: Marriott - Confirmation #MR{random.randint(100000,999999)}",
            "",
            "## Medical (FAKE DATA)",
            f"Insurance: {random.randint(100000,999999)}",
            f"Doctor: Dr. {self._random_string(6)}",
            "",
            "## Important Dates",
            "Anniversary: February 14",
            "Birthday: March 22",
            "",
            "## Notes",
            "Remember to backup the NAS before vacation.",
            "Contact lawyer about the property deed.",
        ]
        return '\n'.join(lines)

    def _documents_content(self):
        """Generate fake document index content.

        ALL DATA BELOW IS COMPLETELY RANDOM AND FAKE.
        """
        lines = [
            "# DECOY FILE - ALL DATA IS RANDOMLY GENERATED",
            "# This is a security canary file for authorized monitoring",
            "# Important Documents Index (FAKE DATA)",
            "",
            "## Tax Returns (FAKE HASHES)",
            "- 2023_Return.pdf (SHA: " + self._random_string(64) + ")",
            "- 2022_Return.pdf (SHA: " + self._random_string(64) + ")",
            "",
            "## Legal",
            "- Lease_Agreement.pdf",
            "- Insurance_Policy.pdf",
            "- Will_and_Testament.pdf",
            "",
            "## Financial",
            "- Bank_Statement_Dec2024.pdf",
            "- Investment_Portfolio.xlsx",
            "- Budget_2025.xlsx",
            "",
            "## Personal",
            "- Passport_Scan.pdf",
            "- Drivers_License.jpg",
            "- Birth_Certificate.pdf",
        ]
        return '\n'.join(lines)

    def get_extension(self, decoy_type):
        extensions = {
            'passwords': '.txt',
            'financial': '.txt',
            'credentials': '.txt',
            'crypto': '.txt',
            'personal': '.txt',
            'documents': '.txt',
        }
        return extensions.get(decoy_type, '.txt')

    def get_filename(self, decoy_type):
        filenames = {
            'passwords': 'passwords',
            'financial': 'financial_records',
            'credentials': 'credentials',
            'crypto': 'crypto_wallets',
            'personal': 'personal_notes',
            'documents': 'document_index',
        }
        return filenames.get(decoy_type, 'canary')
