encryption:
  enabled: false
  key: ''
geofencing:
  alert_on_unknown_location: true
  allowed_countries: []
  allowed_ips: []
  blocked_countries: []
  enabled: false
integrity:
  canary_name: passwords
  canary_path: ''
  enabled: true
  file_hash: 7aaa9d175063b59cb4f5e0ca241b5591996a170510201d1d6a648555588e1d46
logging:
  enabled: true
notifications:
  discord:
    enabled: true
    webhook_url: ''
  telegram:
    bot_token: ''
    chat_id: ''
    enabled: false
process_monitor:
  enabled: true
rate_limit: 5
smtp:
  enabled: false
  from_email: ''
  password: ''
  port: 587
  server: ''
  to_emails: []
  username: ''
threat_intel:
  abuseipdb_api_key: ''
  enabled: false
  virustotal_api_key: ''
